env:
  width: 64
  height: 64
  steps_per_episode: 400
  episodes: 10
  event_threshold: 0.15
  max_speed: 2.5

reservoir:
  size: 512
  spectral_radius: 0.9
  input_scale: 0.5
  leak_rate: 0.3
  sparsity: 0.95
  lr: 0.001

plasticity:
  enabled: true
  lr: 0.0005
  decay: 0.0001

rhythms:
  enabled: true
  theta_hz: 6.0
  gamma_hz: 40.0
  theta_gate_frac: 0.25   # fraction of cycle where learning is allowed
  gamma_gate_frac: 0.5

router:
  enabled: true
  error_window: 20
  novelty_beta: 0.7
  error_threshold: 0.07

memory:
  enabled: true
  max_patterns: 64

training:
  sleep_replay_epochs: 2
  replay_top_k: 8
  seed: 42
